/**
 * Shopify variant IDs for the $249-deposit offer (variants 6b/7b of the
 * Love-vs-Spec 2x2 — docs/plan/AB-TEST-LOVE-VS-SPEC.md).
 *
 * These are SEPARATE Shopify products from the standard $499/$549 deposit
 * products: same configurations, priced $249, with the balance ($750 for the
 * One, $850 for the Premium Bundle) invoiced when the piano ships, exactly
 * like the 50% flow's second half.
 *
 * AUTO-GENERATED by scripts/shopify/create-249-deposit-products.mjs — do not
 * edit by hand. An empty string means "not available": /customize refuses
 * checkout for it rather than silently falling back to a full-price variant.
 */
export const DEPOSIT249_VARIANT_MAP: Record<string, Record<string, Record<string, string>>> = {
    solo: {
        'DS5.5': { 'Black': '53915089961274', 'White': '53915089994042' },
        'DS6.0': { 'Black': '53915090026810', 'White': '53915090059578' },
        'DS6.5': { 'Black': '53915090092346', 'White': '53915090125114' },
    },
    full: {
        'DS5.5': { 'Black': '53915090190650', 'White': '53915090223418' },
        'DS6.0': { 'Black': '53915090256186', 'White': '53915090288954' },
        'DS6.5': { 'Black': '53915090321722', 'White': '53915090354490' },
    },
};
